<div class="container">
    <h2>Unesite ime i sačuvajte ga sa vremenskim podacima</h2>
    <form method="post" action="">
        <div class="form-group">
            <label for="name">Ime:</label>
            <input type="text" name="name" class="form-control" id="name" required>
        </div>
        <div class="form-group">
            <label for="file">Datoteka:</label>
            <input type="file" name="file" id="file">
        </div>
        <button type="submit" class="btn btn-primary">Sačuvaj</button>
    </form>
    <p><?php echo $message ?></p>
</div>
